# Generated by Django 4.1.7 on 2023-05-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=32)),
                ("isSuperAdmin", models.BooleanField(default=False)),
                ("videoNum", models.IntegerField(default=0)),
                ("likeNum", models.IntegerField(default=0)),
                ("collectNum", models.IntegerField(default=0)),
                ("fanNum", models.IntegerField(default=0)),
                ("followNum", models.IntegerField(default=0)),
                ("avatar", models.FileField(upload_to="avatar/")),
                ("createdTime", models.DateTimeField(auto_now_add=True)),
                ("avatarUrl", models.CharField(default="", max_length=128)),
                ("sign", models.CharField(default="", max_length=1024)),
            ],
        ),
    ]
