# Generated by Django 4.1.7 on 2023-05-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("coverUrl", models.CharField(max_length=64)),
                ("videoUrl", models.CharField(max_length=64)),
                ("avatarUrl", models.CharField(max_length=64)),
                ("likeNum", models.IntegerField(default=0)),
                ("collectNum", models.IntegerField(default=0)),
                ("viewNum", models.IntegerField(default=0)),
                ("zone", models.CharField(max_length=64)),
                ("tag", models.CharField(max_length=64)),
                ("createdTime", models.DateField()),
                ("needAudit", models.IntegerField(default=0)),
                (
                    "userID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="user.user",
                    ),
                ),
            ],
        ),
    ]
