# Generated by Django 4.1.7 on 2023-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="userID",
            new_name="userId",
        ),
    ]
