# Generated by Django 4.1.7 on 2023-06-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_rename_userid_video_userid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="avatarUrl",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="video",
            name="coverUrl",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="video",
            name="videoUrl",
            field=models.CharField(max_length=1024),
        ),
    ]
